---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3
    extraPortMappings:
      - containerPort: 30443
        hostPort: 30443
        listenAddress: 0.0.0.0
        protocol: tcp
    extraMounts:
      - containerPath: /opt/data
        hostPath: /Users/zzh/ironman/kind/data
