auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9900
memberlist:
  bind_port: 7940
  advertise_port: 7941
common:
  path_prefix: /data
  storage:
    filesystem:
      chunks_directory: /data/chunks
      rules_directory: /data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2024-04-01
      object_store: filesystem
      store: tsdb
      schema: v13
      index:
        prefix: index_
        period: 24h
