stream_over_http_enabled: true
server:
  http_listen_port: 9100
  grpc_listen_port: 9190
  log_level: info
memberlist:
  bind_port: 7944
  advertise_port: 7945
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tempo/data/generator/wal
  traces_storage:
    path: /tempo/data/generator/traces
storage:
  trace:
    backend: local
    wal:
      path: /tempo/data/wal
    local:
      path: /tempo/data/blocks
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator
      generate_native_histograms: both
